### ISSUE TITLE
Colours not displayed

### ISSUE THREAD

**Issue by shivamsouravjha** [shivamsouravjha/BOOTSTRAP-shape-shifter#1]
When working on online IDE the code Is running great but for offline it isn't chances are for the JS part at the end.

**Comment by Sudhee-bsp** [comment]
I would like to fix it. Please add me as Assignee to this issue :) @shivamsouravjha

**Comment by shivamsouravjha** [comment]
@Sudhee-bsp I've assigned it to you, as far as I know, you've to just add the color to the containers.

**Comment by Sudhee-bsp** [comment]
Done! Added the styles, now its displaying. Waiting to merge the PR :) @shivamsouravjha

**Comment by shivamsouravjha** [comment]
@Sudhee-bsp great work! Merged it!
