### ISSUE TITLE
Deploy to Visualize it

### ISSUE THREAD

**Issue by priyanshnama** [shivamsouravjha/BOOTSTRAP-shape-shifter#11]
@shivamsouravjha 
Deploy the website either on

github pages
heroku
surge
for free to visualize it in real time.

Also update the link in description.

**Comment by shivamsouravjha** [comment]
mind sharing the steps and procedure?

**Comment by priyanshnama** [comment]
@shivamsouravjha 
1. go to [Settings](https://github.com/shivamsouravjha/BOOTSTRAP-shape-shifter/settings).
2. scroll down to **GitHub pages** section.
3. select **master** branch and click on **save**.
4. Finally, You can visualize it [here](https://shivamsouravjha.github.io/BOOTSTRAP-shape-shifter).
5. after it is successfully deployed **add it to description** of repo.
6. changes in **README.md** would be required now which will be done in documentation issue #7

**Comment by shivamsouravjha** [comment]
Thanks!

**Comment by shivamsouravjha** [comment]
check it out [link](https://shivamsouravjha.github.io/BOOTSTRAP-shape-shifter))

**Comment by priyanshnama** [comment]
@shivamsouravjha 
Looks Cool
Now, Kindly add link to about section of repo for easy access.

**Comment by shivamsouravjha** [comment]
@priyanshnama raised it an issues for others to learn contribution
