### ISSUE TITLE
Add Timeout On Each Block

### ISSUE THREAD

**Issue by priyanshnama** [shivamsouravjha/BOOTSTRAP-shape-shifter#12]
@shivamsouravjha 

A **timeout** (of say 3 seconds) can be added on each block.
So that when user clicks and block rises it also **automatically sits back** after 3 seconds.
Would be a **great visual** when clicked on multiple blocks and seeing them sitting down one by one.

I can work on this, Just **assign this to me**.

Moreover, just add **enhancement** and **hacktober** fest tag to this issue.
And add **hacktober-fest** as a topic of your whole repo.

**Comment by shivamsouravjha** [comment]
@priyanshnama go ahead!
