### ISSUE TITLE
Add text at center of containers

### ISSUE THREAD

**Issue by shivamsouravjha** [shivamsouravjha/BOOTSTRAP-shape-shifter#3]
There are total 6 containers and contributors are expected to Add alphabet A....F at the center of each container.

**Comment by zlaytan25** [comment]
Hey I would love to work on this. Would you assign this issue to me?

**Comment by UshasriMavuri1999** [comment]
Hey @shivamsouravjha , Can you please assign this to me?

**Comment by shivamsouravjha** [comment]
@UshasriMavuri1999 I've just another issue try doing it.
@zlaytan25 see that issue too
